---

- name: Setup Debian 12.10 with Deno and Fresh
  hosts: all
  become: yes

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - curl
          - unzip
          - git
          - vim
        state: present
        update_cache: yes
    
    - name: Create a .vimrc file
      file:
        path: ~/.vimrc
        state: touch
        mode: '0644'

    - name: Configure vim
      copy:
        dest: ~/.vimrc
        content: |
          set number
          set tabstop=4
          set ruler
          set smarttab
          set shiftwidth=4
          set expandtab
          set nobackup

          set incsearch
          set ignorecase
          set smartcase
          set showmatch
          set hlsearch

          set wildmenu
          set wildmode=list:longest
          set wildignore=*.docx,*.jpg,*.png,*.git,*.pdf,*.pyc,*.exe,*.flv,*.imp,*.xlsx

          syntax on
          filetype plugin indent on
          set background=dark
          colorscheme slate
          hi Normal guibg=NONE ctermbg=NONE

    - name: Install Deno globally
      shell: |
        curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh
      args:
        creates: /usr/local/bin/deno

    - name: Symlink Deno to /usr/bin
      file:
        src: /usr/local/bin/deno
        dest: /usr/bin/deno
        state: link
        force: yes
    
